config/routes.rb
Rails.application.routes.draw do

  resources :dogs
  resources :events
  resources :users
  get 'access/authenticated'
  get 'access/login'
  get 'access/attempt_login'
  get 'access/logout'
  get 'access/dogmenu'
  get 'access/eventmenu'
  get 'access/admin'
  get 'public/index'
  get 'public/registration'
  get 'public/event_search'
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :event_registrations
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'public#index'
  match ':controller(/:action(/:id))', :via => [:get, :post]

  get 'admin', :to => "access#admin"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  # before_action :valid_user, only: [:edit, :update] <- removing action for non-working method
  before_action :check_expiration, only: [:edit, :update]


  def new
  end

  def index
    redirect_to root_url
  end

  def create
    @user = User.find_by(uemail: params[:password_reset][:uemail].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash[:danger] = "Email sent with password reset instructions"
      redirect_to root_url
    end
  end

  def edit
  end

  def update
    if password_blank?
      flash.now[:danger] = "Password can't be blank"
      render 'edit'
    elsif @user.update_attributes(user_params)
      flash[:success] = "Password has been reset."
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  # Returns true if password is blank.
  def password_blank?
    params[:user][:password].blank?
  end

  def get_user
    @user = User.find_by(uemail: params[:uemail])
  end

  # This method doesn't work as expected.
  # def valid_user
  #   unless @user.email_activate
  #     flash[:danger] = "Your account has not been activated, you cannot perform a password reset"
  #     redirect_to root_url
  #   end
  # end

  # Checks expiration of reset token.
  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired."
      redirect_to new_password_reset_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset Password') %>
<h1>Reset Password</h1>

<%= render 'shared/flash_error_messages' %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
    <%= render 'shared/error_messages', object: f.object  %>
    <%= hidden_field_tag :uemail, @user.uemail %>

    <%= f.label :password, "Password" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Password confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot Password") %>
<h1>Forgot Password</h1>

<%= render 'shared/flash_error_messages' %>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
        <%= f.label :uemail %>
        <%= f.email_field :uemail, class: 'form-control' %>

        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Home', root_path %>