config/routes.rb
Rails.application.routes.draw do

  resources :dogs
  resources :events
  resources :users
  get 'access/authenticated'
  get 'access/login'
  get 'access/attempt_login'
  get 'access/logout'
  get 'access/dogmenu'
  get 'access/eventmenu'
  get 'access/admin'
  get 'public/index'
  get 'public/registration'
  get 'public/event_search'
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :event_registrations
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'public#index'
  match ':controller(/:action(/:id))', :via => [:get, :post]

  get 'admin', :to => "access#admin"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :dogs, dependent: :destroy
  #Attendees are USERS
  has_many :created_events, class_name: Event, foreign_key: :creator_id, :dependent => :destroy
  has_many :event_registrations, foreign_key: :attendee_id, :dependent => :destroy
  has_many :attended_events, through: :event_registrations, source: :event
  attr_accessor :reset_token
  has_secure_password
  before_create :confirmation_token
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :username,
            :length => { :within => 4..25 },
            :uniqueness => true,
            :presence => true
  validates :uemail,
            :presence => true,
            :uniqueness => true,
            :format => EMAIL_REGEX

  validates :password,
            :presence => true,
            :length => { :minimum => 8 }
  validates_confirmation_of :password

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  # Sets the password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_set_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired
  def password_reset_expired?
    reset_set_at < 2.hours.ago
  end

  # Generates token for password reset functionality
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def upcoming_events
    event_registrations.where("date >= ?", DateTime.current)
  end

  def previous_events
    event_registrations.where("date < ?", DateTime.current)
  end

  private
  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

  # Converts email to all lower-case
  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :confirm_logged_in, except: [:create, :confirm_email]
  before_filter :admin_only, except: [:show, :edit, :update, :create, :confirm_email]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # Show will just display other user's profiles to admins, regular users can only see their own prof.
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_url, flash: {notice: "Access denied."}
      end
    end
    @attended_events = @user.attended_events.paginate(page: params[:page], per_page: 4)
    @created_events = @user.created_events.paginate(page: params[:page], per_page: 4)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_url, flash: {notice: "Access denied."}
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    #Added mailer action here to deliver mail when successful or display error went user creation didn't work.
    respond_to do |format|
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        format.html { redirect_to root_url, notice: 'Please confirm your email address to continue' }
      else
          format.html { render 'public/registration' }
      end
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = "Welcome to Dogspace! Your email has been confirmed. Please Log In to continue"
      redirect_to access_login_path
    else
      flash[:error] = "Your activation link has expired"
      redirect_to root_url
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        unless current_user.admin?
          unless @user == current_user
            redirect_to root_url, flash: {notice: "Access denied."}
          end
        end
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # TODO Check if the role= param can be sent be regular users to create admins.
    def user_params
      params.require(:user).permit(:ufname, :umname, :ulname, :uemail, :username, :password,
                                   :email_confirmation, :password_confirmation, :role, :reset_digest, :reset_set_at,
                                   :city, :state, :zip)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.uemail.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.ufname, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label 'First Name' %><br>
    <%= f.text_field :ufname %>
  </div>
  <div class="field">
    <%= f.label 'Middle Name' %><br>
    <%= f.text_field :umname %>
  </div>
  <div class="field">
    <%= f.label 'Last Name' %><br>
    <%= f.text_field :ulname %>
  </div>
  <div class="field">
    <%= f.label 'E-mail address' %><br>
    <%= f.text_field :uemail %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label 'City' %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label 'State' %><br>
    <%= select_tag :state, options_for_select(us_states) %>
  </div>
  <div class="field">
    <%= f.label 'Zip' %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>


    <% if session[:user_id] %>
        <% if @current_user.try(:admin?) %>
            <div class="field">
              <%= f.label :role %><br>
              <%= f.select(:role, User.roles.keys.map {|role| [role.titleize, role]}) %>
            </div>
        <% end %>
    <% end %>

  <div class="actions">
    <%= f.submit 'Update Profile' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<p>To change your avatar picture which is linked to your email address click <%= link_to 'Here', 'http://en.gravatar.com/' %></p>
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', access_authenticated_path %>
<% if session[:user_id] %>
    <% if @current_user.try(:admin?) %>
        | <%= link_to 'Users', users_path %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sport Dog Network Registered Users</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>E-mail Address</th>
      <th>Username</th>
      <th>Role</th>
      <th>Email Confirmed?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.ufname %></td>
        <td><%= user.umname %></td>
        <td><%= user.ulname %></td>
        <td><%= user.uemail %></td>
        <td><%= user.username %></td>
        <td><%= user.role %></td>
        <td><%= user.email_confirmed %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Admin Menu', access_admin_url %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Admin Panel', access_admin_path %>
<% if session[:user_id] %>
    <% if @current_user.try(:admin?) %>
        <%= link_to 'Users', users_path %>
    <% end %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, @user.ufname) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.ufname + " " + @user.ulname %>
</h1>

<p>
  <strong>First Name:</strong>
  <%= @user.ufname %>
</p>

<p>
  <strong>Middle Name:</strong>
  <%= @user.umname %>
</p>

<p>
  <strong>Last Name</strong>
  <%= @user.ulname %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @user.uemail %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit Profile', edit_user_path(@user) %> |
<% if session[:user_id] %>
    <% if @current_user.try(:admin?) %>
        <%= link_to 'Users', access_admin_path %>
    <% else %>
        <%= link_to 'Back', access_authenticated_path %>
    <% end %>
<% end %>