config/routes.rb
Rails.application.routes.draw do

  resources :dogs
  resources :events
  resources :users
  get 'access/authenticated'
  get 'access/login'
  get 'access/attempt_login'
  get 'access/logout'
  get 'access/dogmenu'
  get 'access/eventmenu'
  get 'access/admin'
  get 'public/index'
  get 'public/registration'
  get 'public/event_search'
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :event_registrations
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'public#index'
  match ':controller(/:action(/:id))', :via => [:get, :post]

  get 'admin', :to => "access#admin"

end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  before_action :confirm_logged_in, :except => [:login, :attempt_login, :logout]
  before_filter :admin_only, :only => :admin

  def authenticated
    #Displays a regular  user menu
  end

  def dogmenu
    #Displays the dog menu
    @dogs = current_user.dogs
  end

  def eventmenu
    #Displays the event menu
    @e_attending = current_user.attended_events.paginate(page: params[:page], per_page: 5)
    @e_created = current_user.created_events.paginate(page: params[:page], per_page: 5)
  end

  def login
    #Displays the login form
  end

  def admin
    #Displays the admin menu
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(:username => params[:username]).first
      if found_user
        #This nested if will check if the email_confirmed attribute is set to TRUE in order to proceed with
        # authentication.
        if found_user.email_confirmed
            authorized_user = found_user.authenticate(params[:password])
        else
          flash.now[:error] = "Please activate your account by clicking the activation link sent to your email"
        end
      end
    end
    if authorized_user
      # mark user as logged in
      session[:user_id] = authorized_user.id
      session[:username] = authorized_user.username
      flash[:notice] = "You are now logged in."
      # These two if statements wll check if the user has a session and if the user is an admin.
      # If the user is an admin then it will be redirected to access/admin otherwise to access/authenticated.
      if session[:user_id]
        if authorized_user.try(:admin?)
            redirect_to(:action => 'admin')
        else
        redirect_to(:action => 'authenticated')
        end
      end
    else
      flash[:error] = "Invalid username/password combination."
      redirect_to(:action => 'login')
    end
  end

  def logout
    # mark user as logged out
    session[:user_id] = nil
    session[:username] = nil
    flash[:notice] = "Logged out"
    redirect_to(:action => "login")
  end
end

app/helpers/access_helper.rb
module AccessHelper

  # Adding this login functionality for Update in password_resets_controller.rb to work
  def log_in(user)
    session[:user_id] = user.id
  end

  # The famous current user method, added later on so that the application can work with most tuts.
  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

end

app/views/access/admin.html.erb
<% @page_title = "Admin Menu" %>

<div class="menu">
  <h1>SDN Administrator Menu</h1>
  <div class="identity">Logged in as: <%= session[:username] %></div>
  <ul>
    <li><%= link_to "Manage Users", users_path %></li>
    <li><%= link_to "Manage Dogs", dogs_path %></li>
    <li><%= link_to "Manage Events", events_path %></li>
    <li><%= link_to("Logout", :action => 'logout') %></li>
  </ul>
</div>

app/views/access/attempt_login.html.erb
<h1>Access#attempt_login</h1>
<p>Find me in app/views/access/attempt_login.html.erb</p>

app/views/access/authenticated.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<% @page_title = "User Menu" %>

<div class="menu">
  <h1>User Menu</h1>
  <div class="identity">Logged in as: <%= session[:username] %></div>
  <ul>
    <li><%= link_to("My Profile", user_path(session[:user_id])) %></li>
    <li><%= link_to "My Dogs", access_dogmenu_path %></li>
    <li><%= link_to "My Events", access_eventmenu_path %></li>
    <li><%= link_to("Logout", :action => 'logout') %></li>
  </ul>
</div>

app/views/access/dogmenu.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<%= render 'shared/flash_error_messages' %>

<% @page_title = "My Dogs" %>

<div class="menu">
  <h1>My Dogs</h1>
  <ul>
    <li><%= link_to("User Menu", access_authenticated_path) %></li>
    <li><%= link_to "Add Dog", new_dog_path %></li>
    <li><%= link_to "Back", access_authenticated_path %></li>
  </ul>
</div>

<div id="dogdisplay">
  <table>
    <tr>
      <th>Dog Name</th>
      <th>Breed</th>
    </tr>
    <% @dogs.each do |d| %>
    <tr>
      <td><%= link_to d.dname, d %></td>
      <td><%= d.breed %></td>
      <td><%= link_to "Edit", edit_dog_path(d) %></td>
      <td><%= link_to "Delete", d, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/access/eventmenu.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<% @page_title = "My Events" %>

<div class="menu">
  <h1>My Events</h1>
  <ul>
    <li><%= link_to("User Menu", access_authenticated_path) %></li>
    <li><%= link_to "Search Events", public_event_search_path %></li>
    <li><%= link_to "Create New Event", new_event_path %></li>

  </ul>
</div>
<p>
<p><h2>Created Events</h2></p>
<div id="created-events">
  <table>
    <tr>
      <th>Event Name</th>
      <th>Date</th>
      <th>Time</th>
    </tr>
    <% @e_created.each do |c| %>
        <tr>
          <td><%= link_to c.ename, (c) %></td>
          <td><%= c.edate %></td>
          <td><%= c.etime %></td>
          <td><%= link_to "Edit", edit_event_path(c) %></td>
          <td><%= link_to "Delete Event", c, method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
    <% end %>
  </table>
</div>
<p>
  <%= will_paginate @e_created %>
</p>
<p><h2>Attending Events</h2></p>
<div id="attending-events">
  <table>
    <tr>
      <th>Event Name</th>
      <th>Date</th>
      <th>Time</th>
    </tr>
    <% @e_attending.each do |e| %>
        <tr>
          <td><%= link_to e.ename, (e) %></td>
          <td><%= e.edate %></td>
          <td><%= e.etime %></td>
        </tr>
    <% end %>
  </table>
</div>
<p>
  <%= will_paginate @e_attending %>
</p>

app/views/access/login.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>
<%= render 'shared/flash_error_messages' %>

<% @page_title = "SDN Login Page" %>

<div class="login">
  <%= form_tag(:action => 'attempt_login') do %>
      <table>
        <tr>
          <td><%= label_tag :username %></td>
          <td><%= text_field_tag :username %></td>
        </tr>
        <tr>
          <td><%= label_tag :password %></td>
          <td><%= password_field_tag :password %></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td><%= submit_tag("Log In") %></td>
        </tr>
      </table>
  <% end %>
</div>

<%= link_to('Home', root_url) %>

app/views/access/logout.html.erb
<h1>Access#logout</h1>
<p>Find me in app/views/access/logout.html.erb</p>